### ISSUE TITLE
Always the same initial lat lng?

### ISSUE THREAD

**Issue by lasd14** [eopeter/flutter_mapbox_navigation#157]
Hello I have this problem...
When I change in the initialLat and initialLng options it doesn't work, I always have the same position.
![Screenshot_1644512939](https://user-images.githubusercontent.com/51976094/153460027-e64e6ecd-790b-4e21-aad6-2e25188d20ba.png)

**Comment by eopeter** [comment]
Stale issue message

**Comment by neildunlop** [comment]
Is there anything in the error log?  This can sometimes be because things have not been initialised correctly (something in your setup may not be configured correctly), or there may be an issue with determining location (permissions, simulator issues).  We need a bit more info to provide a bit more help.
