### ISSUE TITLE
Navigation Crashes for Android Target SDK 31+

### ISSUE THREAD

**Issue by rhyadav** [eopeter/flutter_mapbox_navigation#325]
For Android Target SDK 31+ the navigation crashes, due to FLAG_IMMUTABLE error, it works fine below SDK 29. Error below
`E/MapboxModuleProvider( 9851): Module loading failed
E/MapboxModuleProvider( 9851): java.lang.reflect.InvocationTargetException
E/MapboxModuleProvider( 9851): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/MapboxModuleProvider( 9851): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/MapboxModuleProvider( 9851): 	at com.mapbox.common.module.provider.MapboxModuleProvider$defaultMapboxModuleCreator$1.getInstance(MapboxModuleProvider.kt:138)
E/MapboxModuleProvider( 9851): 	at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider( 9851): 	at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider( 9851): 	at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider( 9851): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.fetchRoute(NavigationActivity.kt:107)
E/MapboxModuleProvider( 9851): 	at com.dormmom.flutter_mapbox_navigation.activity.NavigationActivity.onNavigationReady(NavigationActivity.kt:94)
E/MapboxModuleProvider( 9851): 	at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:653)
E/MapboxModuleProvider( 9851): 	at com.mapbox.navigation.ui.NavigationView.access$700(NavigationView.java:75)
E/MapboxModuleProvider( 9851): 	at com.mapbox.navigation.ui.NavigationView$1.onStyleLoaded(NavigationView.java:247)
E/MapboxModuleProvider( 9851): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
E/MapboxModuleProvider( 9851): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
E/MapboxModuleProvider( 9851): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1375)
E/MapboxModuleProvider( 9851): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/MapboxModuleProvider( 9851): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
E/MapboxModuleProvider( 9851): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MapboxModuleProvider( 9851): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MapboxModuleProvider( 9851): 	at android.os.Looper.loopOnce(Looper.java:161)
E/MapboxModuleProvider( 9851): 	at android.os.Looper.loop(Looper.java:288)
E/MapboxModuleProvider( 9851): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MapboxModuleProvider( 9851): 	at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider( 9851): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MapboxModuleProvider( 9851): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MapboxModuleProvider( 9851): Caused by: java.lang.IllegalArgumentException: com.example.mapbox_learning: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MapboxModuleProvider( 9851): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

**Comment by aleonnet** [comment]
@eopeter Thank you for the nice library! I've build to SDK 31/Android 12 and the App does not crash in my case, but there are memory leaks reported by LeakCanary. The iOS build seems to be issue free.

┬───
│ GC Root: System class
│
├─ android.content.res.Resources class
│    Leaking: NO (a class is never leaking)
│    ↓ static Resources.sAppContext
│                       ~~~~~~~~~~~
├─ android.app.ContextImpl instance
│    Leaking: UNKNOWN
│    Retaining 2.1 kB in 22 objects
│    mOuterContext instance of android.app.ContextImpl
│    ContextImpl.mOuterContext == ContextImpl.this: not tied to any particular
│    lifecycle
│    ↓ ContextImpl.mPackageInfo
│                  ~~~~~~~~~~~~
├─ android.app.LoadedApk instance
│    Leaking: UNKNOWN
│    Retaining 2.4 MB in 33026 objects
│    mApplication instance of android.app.Application
│    Receivers
│    ..NavigationActivity@328998736
│    ....NavigationActivity$onCreate$4@330364768
│    ....NavigationActivity$onCreate$3@330364832
│    ..NavigationActivity@328999208
│    ....NavigationActivity$onCreate$3@329011128
│    ....NavigationActivity$onCreate$4@329011192
│    ..Application@317211512
│    ....AndroidBatteryMonitor$broadcastReceiver$1@328999840
│    ....LocationServiceImpl$LocationModeChangedBroadcastReceiver@328999904
│    ....VisibilityTracker@328999968
│    ....ConnectionChangeReceiver@329000040
│    ↓ LoadedApk.mReceivers
│                ~~~~~~~~~~
├─ android.util.ArrayMap instance
│    Leaking: UNKNOWN
│    Retaining 2.4 MB in 32981 objects
│    ↓ ArrayMap.mArray
│               ~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 2.4 MB in 32979 objects
│    ↓ Object[0]
│            ~~~
╰→ com.eopeter.fluttermapboxnavigation.activity.NavigationActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.eopeter.
​     fluttermapboxnavigation.activity.NavigationActivity received
​     Activity#onDestroy() callback and Activity#mDestroyed is true)
​     Retaining 900.1 kB in 9710 objects
​     key = 852ec58c-ca2d-4dcf-814e-0dde94351340
​     watchDurationMillis = 5451
​     retainedDurationMillis = 450
​     mApplication instance of android.app.Application
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper

METADATA

Build.VERSION.SDK_INT: 31
Build.MANUFACTURER: samsung
LeakCanary version: 2.9.1
App process name: com.eopeter.fluttermapboxnavigationexample
Class count: 31041
Instance count: 289217
Primitive array count: 184343
Object array count: 42790
Thread count: 76
Heap total bytes: 34980489
Bitmap count: 17
Bitmap total bytes: 18332248
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/com.eopeter.
fluttermapboxnavigationexample/no_backup/androidx.work.workdb
Db 2: open /data/user/0/com.eopeter.
fluttermapboxnavigationexample/databases/leaks.db
Stats: LruCache[maxSize=3000,hits=134720,misses=267193,hitRate=33%]
RandomAccess[bytes=13797762,reads=267193,travel=101077755725,range=42772479,size
=52196799]
Analysis duration: 91538 ms 

![Screenshot_20231105-175507](https://github.com/eopeter/flutter_mapbox_navigation/assets/20618327/e60a08bc-83c5-4923-a8bf-b81d95f725eb)

**Comment by eopeter** [comment]
Stale issue message
