### ISSUE TITLE
NavigationActivity Leaked

### ISSUE THREAD

**Issue by tipsy-tips** [eopeter/flutter_mapbox_navigation#328]
Having this issue whenever i cancelled a trip or navigation the app will freeze for a moment and will show that canary found a leak. The app continue to work after dumping the error however the app sometimes consistently show a prompt that it is not responding. The error only occurs in debug app. The released app works fine.

I am currently using flutter_mapbox_navigation: 0.2.2

Here's the analysis came from Canary leak:

┬───
│ GC Root: System class
│
├─ [android.provider.FontsContract](http://android.provider.fontscontract/) class
│    Leaking: NO (Application↓ is not leaking and a class is never leaking)
│    ↓ static [FontsContract.sContext](http://fontscontract.scontext/)
├─ [android.app.Application](http://android.app.application/) instance
│    Leaking: NO (Application is a singleton)
│    mBase instance of [android.app.ContextImpl](http://android.app.contextimpl/)
│    ↓ [Application.mLoadedApk](http://application.mloadedapk/)
│                  ~~~~~~~~~~
├─ [android.app.LoadedApk](http://android.app.loadedapk/) instance
│    Leaking: UNKNOWN
│    Retaining [1.9](tel:1.9) MB in [26048](tel:26048) objects
│    mApplication instance of [android.app.Application](http://android.app.application/)
│    Receivers
│    ..NavigationActivity@[317893520](tel:317893520)
│    ....NavigationActivity$onCreate$4@[321884064](tel:321884064)
│    ....NavigationActivity$onCreate$3@[321884128](tel:321884128)
│    ..NavigationActivity@[317893992](tel:317893992)
│    ....NavigationActivity$onCreate$3@[317903744](tel:317903744)
│    ....NavigationActivity$onCreate$4@[317903808](tel:317903808)
│    ..Application@[315405360](tel:315405360)
│    ....LocationServiceStatusReceiver@[317891680](tel:317891680)
│    ....AndroidBatteryMonitor$broadcastReceiver$1@[317894664](tel:317894664)
│    ....VisibilityTracker@[317894728](tel:317894728)
│    ....LocationServiceImpl$LocationModeChangedBroadcastReceiver@[317894800](tel:317894800)
│    ....ConnectionChangeReceiver@[317894864](tel:317894864)
│    ↓ [LoadedApk.mReceivers](http://loadedapk.mreceivers/)
│                ~~~~~~~~~~
├─ [android.util.ArrayMap](http://android.util.arraymap/) instance
│    Leaking: UNKNOWN
│    Retaining [1.9](tel:1.9) MB in [25976](tel:25976) objects
│    ↓ [ArrayMap.mArray](http://arraymap.marray/)
│               ~~~~~~
├─ [java.lang.Object](http://java.lang.object/)[] array
│    Leaking: UNKNOWN
│    Retaining [1.9](tel:1.9) MB in [25974](tel:25974) objects
│    ↓ Object[0]
│            ~~~
╰→ [com.eopeter.fluttermapboxnavigation.activity.NavigationActivity](http://com.eopeter.fluttermapboxnavigation.activity.navigationactivity/) instance
​     Leaking: YES (ObjectWatcher was watching this because [com.eopeter](http://com.eopeter/).
​     [fluttermapboxnavigation.activity.NavigationActivity](http://fluttermapboxnavigation.activity.navigationactivity/) received
​     Activity#onDestroy() callback and Activity#mDestroyed is true)
​     Retaining [892.7](tel:892.7) kB in [12200](tel:12200) objects
​     key = 8bbe[1273](tel:1273)-e[849-4](tel:849-4)d8b-9aa[1-44](tel:1-44)fdc[32464](tel:32464)b2
​     watchDurationMillis = [5739](tel:5739)
​     retainedDurationMillis = [739](tel:739)
​     mApplication instance of [android.app.Application](http://android.app.application/)
​     mBase instance of [androidx.appcompat.view.ContextThemeWrapper](http://androidx.appcompat.view.contextthemewrapper/)

METADATA

[Build.VERSION](http://build.version/).SDK_INT: 33
[Build.MANUFACTURER](http://build.manufacturer/): Xiaomi
LeakCanary version: [2.9.1](tel:2.9.1)
App process name: [com.spc](http://com.spc/).tourism_app
Class count: [34018](tel:34018)
Instance count: [289800](tel:289800)
Primitive array count: [170765](tel:170765)
Object array count: [45509](tel:45509)
Thread count: 85
Heap total bytes: [35596762](tel:35596762)
Bitmap count: 19
Bitmap total bytes: [10948538](tel:10948538)
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/[com.spc](http://com.spc/).tourism_app/databases/firestore.%5BDEFAULT%5D.
spctourismapp.%28default%29
Db 2: open /data/user/0/[com.spc](http://com.spc/).tourism_app/no_backup/[androidx.work.workdb](http://androidx.work.workdb/)
Stats: LruCache[maxSize=[3000](tel:3000),hits=[139900](tel:139900),misses=[289353](tel:289353),hitRate=32%]
RandomAccess[bytes=[15241431](tel:15241431),reads=[289353](tel:289353),travel=[129776904119](tel:129776904119),range=[43567639](tel:43567639),size
=[52356498](tel:52356498)]
Analysis duration: [72292](tel:72292) ms

**Comment by Hermit90** [comment]
Hi I have the same error

┬───
│ GC Root: Global variable in native code
│
├─ android.app.Application instance
│ Leaking: NO (Application is a singleton)
│ mBase instance of android.app.ContextImpl
│ ↓ Application.mLoadedApk
│ ~~~~~~~~~~
├─ android.app.LoadedApk instance
│ Leaking: UNKNOWN
│ Retaining 12.6 MB in 370974 objects
│ mApplication instance of android.app.Application
│ Receivers
│ ..NavigationActivity@328871776
│ ....NavigationActivity$onCreate$3@341497440
│ ....NavigationActivity$onCreate$4@341497504
│ ..NavigationActivity@328872248
│ ....NavigationActivity$onCreate$3@340936272
│ ....NavigationActivity$onCreate$4@340936336
│ ..Application@320915080
│ ....bkt@328658176
│ ....NetworkStateChangeReceiver30186@322078384
│ ....LocationServiceImpl$LocationModeChangedBroadcastReceiver@340921488
│ ....ConnectionChangeReceiver@340921552
│ ....btz@328658824
│ ....NetworkStateChangeReceiver33947@322069232
│ ....du@323747576
│ ....VisibilityTracker@340921696
│ ....LocationServiceStatusReceiver@340921768
│ ....an@323927240
│ ....AndroidBatteryMonitor$broadcastReceiver$1@340921880
│ ..NavigationActivity@328872752
│ ....NavigationActivity$onCreate$4@330313768
│ ....NavigationActivity$onCreate$3@330313832
│ ..ContextImpl@323678728
│ ....fda@330312600
│ ..NavigationActivity@328873256
│ ....NavigationActivity$onCreate$4@329751440
│ ....NavigationActivity$onCreate$3@329751504
│ ..NavigationActivity@328873728
│ ....NavigationActivity$onCreate$4@328874280
│ ....NavigationActivity$onCreate$3@328874344
│ ↓ LoadedApk.mReceivers
│ ~~~~~~~~~~
├─ android.util.ArrayMap instance
│ Leaking: UNKNOWN
│ Retaining 12.6 MB in 370894 objects
│ ↓ ArrayMap.mArray
│ ~~~~~~
├─ java.lang.Object[] array
│ Leaking: UNKNOWN
│ Retaining 12.6 MB in 370892 objects
│ ↓ Object[12]
│ ~~~~
╰→ com.eopeter.fluttermapboxnavigation.activity.NavigationActivity instance
​ Leaking: YES (ObjectWatcher was watching this because com.eopeter.
​ fluttermapboxnavigation.activity.NavigationActivity received
​ Activity#onDestroy() callback and Activity#mDestroyed is true)
​ Retaining 765.5 kB in 9331 objects
​ key = 4149cb05-4ddf-4316-8320-2d43d9d8564b
​ watchDurationMillis = 2572724
​ retainedDurationMillis = 2567723
​ mApplication instance of android.app.Application
​ mBase instance of androidx.appcompat.view.ContextThemeWrapper

METADATA

Build.VERSION.SDK_INT: 31
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.9.1
App process name: one.blackops.babigo_driver
Class count: 42166
Instance count: 663954
Primitive array count: 260129
Object array count: 93680
Thread count: 155
Heap total bytes: 55601060
Bitmap count: 140
Bitmap total bytes: 7519628
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/one.blackops.babigo_driver/no_backup/androidx.work.
workdb
Db 2: open /data/user/0/one.blackops.babigo_driver/databases/com.google.android.
datatransport.events
Db 3: open /data/user/0/one.blackops.babigo_driver/databases/leaks.db
Stats: LruCache[maxSize=3000,hits=220840,misses=622425,hitRate=26%]
RandomAccess[bytes=30790772,reads=622425,travel=632356740574,range=71247866,size
=81988115]
Analysis duration: 230318 ms

**Comment by samargy** [comment]
Same error here as well

D/LeakCanary(10863): HEAP ANALYSIS RESULT
D/LeakCanary(10863): ====================================
D/LeakCanary(10863): 2 APPLICATION LEAKS
D/LeakCanary(10863): 
D/LeakCanary(10863): References underlined with "~~~" are likely causes.
D/LeakCanary(10863): Learn more at https://squ.re/leaks.
D/LeakCanary(10863): 
D/LeakCanary(10863): 36012 bytes retained by leaking objects
D/LeakCanary(10863): Signature: 9aba135f78ed9d1ddf0e505b45e4b9dc3e7b0e2d
D/LeakCanary(10863): ┬───
D/LeakCanary(10863): │ GC Root: Thread object
D/LeakCanary(10863): │
D/LeakCanary(10863): ├─ android.os.HandlerThread instance
D/LeakCanary(10863): │    Leaking: NO (PathClassLoader↓ is not leaking)
D/LeakCanary(10863): │    Thread name: 'LeakCanary-Heap-Dump'
D/LeakCanary(10863): │    ↓ Thread.contextClassLoader
D/LeakCanary(10863): ├─ dalvik.system.PathClassLoader instance
D/LeakCanary(10863): │    Leaking: NO (FlutterMapboxNavigationPlugin↓ is not leaking and A ClassLoader is never leaking)
D/LeakCanary(10863): │    ↓ ClassLoader.runtimeInternalObjects
D/LeakCanary(10863): ├─ java.lang.Object[] array
D/LeakCanary(10863): │    Leaking: NO (FlutterMapboxNavigationPlugin↓ is not leaking)
D/LeakCanary(10863): │    ↓ Object[4050]
D/LeakCanary(10863): ├─ com.eopeter.fluttermapboxnavigation.FlutterMapboxNavigationPlugin class
D/LeakCanary(10863): │    Leaking: NO (a class is never leaking)
D/LeakCanary(10863): │    ↓ static FlutterMapboxNavigationPlugin.binaryMessenger
D/LeakCanary(10863): │                                           ~~~~~~~~~~~~~~~
D/LeakCanary(10863): ├─ io.flutter.embedding.engine.dart.DartExecutor instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 11.8 kB in 362 objects
D/LeakCanary(10863): │    ↓ DartExecutor.flutterJNI
D/LeakCanary(10863): │                   ~~~~~~~~~~
D/LeakCanary(10863): ├─ io.flutter.embedding.engine.FlutterJNI instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 232 B in 15 objects
D/LeakCanary(10863): │    ↓ FlutterJNI.localizationPlugin
D/LeakCanary(10863): │                 ~~~~~~~~~~~~~~~~~~
D/LeakCanary(10863): ├─ io.flutter.plugin.localization.LocalizationPlugin instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 32 B in 2 objects
D/LeakCanary(10863): │    context instance of com.example.dgr_app.MainActivity with mDestroyed = true
D/LeakCanary(10863): │    ↓ LocalizationPlugin.context
D/LeakCanary(10863): │                         ~~~~~~~
D/LeakCanary(10863): ╰→ com.example.dgr_app.MainActivity instance
D/LeakCanary(10863): ​     Leaking: YES (ObjectWatcher was watching this because com.example.dgr_app.MainActivity received
D/LeakCanary(10863): ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
D/LeakCanary(10863): ​     Retaining 36.0 kB in 601 objects
D/LeakCanary(10863): ​     key = af9a762a-d155-4968-a0a7-b1071e50fadf
D/LeakCanary(10863): ​     watchDurationMillis = 5198
D/LeakCanary(10863): ​     retainedDurationMillis = 198
D/LeakCanary(10863): ​     mApplication instance of android.app.Application
D/LeakCanary(10863): ​     mBase instance of android.app.ContextImpl
D/LeakCanary(10863): 
D/LeakCanary(10863): 1129434 bytes retained by leaking objects
D/LeakCanary(10863): Signature: 68816b2b655b7c5a606b21befdb1e1309c29a20f
D/LeakCanary(10863): ┬───
D/LeakCanary(10863): │ GC Root: Thread object
D/LeakCanary(10863): │
D/LeakCanary(10863): ├─ android.os.HandlerThread instance
D/LeakCanary(10863): │    Leaking: NO (PathClassLoader↓ is not leaking)
D/LeakCanary(10863): │    Thread name: 'LeakCanary-Heap-Dump'
D/LeakCanary(10863): │    ↓ Thread.contextClassLoader
D/LeakCanary(10863): ├─ dalvik.system.PathClassLoader instance
D/LeakCanary(10863): │    Leaking: NO (FlutterMapboxNavigationPlugin↓ is not leaking and A ClassLoader is never leaking)
D/LeakCanary(10863): │    ↓ ClassLoader.runtimeInternalObjects
D/LeakCanary(10863): ├─ java.lang.Object[] array
D/LeakCanary(10863): │    Leaking: NO (FlutterMapboxNavigationPlugin↓ is not leaking)
D/LeakCanary(10863): │    ↓ Object[4050]
D/LeakCanary(10863): ├─ com.eopeter.fluttermapboxnavigation.FlutterMapboxNavigationPlugin class
D/LeakCanary(10863): │    Leaking: NO (a class is never leaking)
D/LeakCanary(10863): │    ↓ static FlutterMapboxNavigationPlugin.eventSink
D/LeakCanary(10863): │                                           ~~~~~~~~~
D/LeakCanary(10863): ├─ io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 28 B in 2 objects
D/LeakCanary(10863): │    ↓ EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.this$1
D/LeakCanary(10863): │                                                                        ~~~~~~
D/LeakCanary(10863): ├─ io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 56 B in 3 objects
D/LeakCanary(10863): │    ↓ EventChannel$IncomingStreamRequestHandler.handler
D/LeakCanary(10863): │                                                ~~~~~~~
D/LeakCanary(10863): ├─ com.eopeter.fluttermapboxnavigation.models.views.EmbeddedNavigationMapView instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 1.1 MB in 13263 objects
D/LeakCanary(10863): │    activity instance of com.example.dgr_app.MainActivity with mDestroyed = true
D/LeakCanary(10863): │    context instance of com.example.dgr_app.MainActivity with mDestroyed = true
D/LeakCanary(10863): │    ↓ TurnByTurn.binding
D/LeakCanary(10863): │                 ~~~~~~~
D/LeakCanary(10863): ├─ com.eopeter.fluttermapboxnavigation.databinding.NavigationActivityBinding instance
D/LeakCanary(10863): │    Leaking: UNKNOWN
D/LeakCanary(10863): │    Retaining 1.1 MB in 13144 objects
D/LeakCanary(10863): │    ↓ NavigationActivityBinding.navigationView
D/LeakCanary(10863): │                                ~~~~~~~~~~~~~~
D/LeakCanary(10863): ├─ com.mapbox.navigation.dropin.NavigationView instance
D/LeakCanary(10863): │    Leaking: YES (View.mContext references a destroyed activity)
D/LeakCanary(10863): │    Retaining 1.1 MB in 13143 objects
D/LeakCanary(10863): │    View not part of a window view hierarchy
D/LeakCanary(10863): │    View.mAttachInfo is null (view detached)
D/LeakCanary(10863): │    View.mID = R.id.navigationView
D/LeakCanary(10863): │    View.mWindowAttachCount = 1
D/LeakCanary(10863): │    mContext instance of com.example.dgr_app.MainActivity with mDestroyed = true
D/LeakCanary(10863): │    ↓ NavigationView.navigationContext
D/LeakCanary(10863): ├─ com.mapbox.navigation.dropin.navigationview.NavigationViewContext instance
D/LeakCanary(10863): │    Leaking: YES (NavigationView↑ is leaking)
D/LeakCanary(10863): │    Retaining 81.1 kB in 515 objects
D/LeakCanary(10863): │    context instance of com.example.dgr_app.MainActivity with mDestroyed = true
D/LeakCanary(10863): │    ↓ NavigationViewContext.viewModel
D/LeakCanary(10863): ╰→ com.mapbox.navigation.dropin.navigationview.NavigationViewModel instance
D/LeakCanary(10863): ​     Leaking: YES (ObjectWatcher was watching this because com.mapbox.navigation.dropin.navigationview.
D/LeakCanary(10863): ​     NavigationViewModel received ViewModel#onCleared() callback)
D/LeakCanary(10863): ​     Retaining 677 B in 26 objects
D/LeakCanary(10863): ​     key = 00d52c18-04bd-4915-bee2-f0b7f3235e1d
D/LeakCanary(10863): ​     watchDurationMillis = 5199
D/LeakCanary(10863): ​     retainedDurationMillis = 199
D/LeakCanary(10863): ====================================

METADATA
D/LeakCanary(10863): Build.VERSION.SDK_INT: 33
D/LeakCanary(10863): Build.MANUFACTURER: Google
D/LeakCanary(10863): LeakCanary version: 2.9.1
D/LeakCanary(10863): App process name: com.example.dgr_app
D/LeakCanary(10863): Class count: 30839
D/LeakCanary(10863): Instance count: 286024
D/LeakCanary(10863): Primitive array count: 163691
D/LeakCanary(10863): Object array count: 41475
D/LeakCanary(10863): Thread count: 74
D/LeakCanary(10863): Heap total bytes: 32120430
D/LeakCanary(10863): Bitmap count: 8
D/LeakCanary(10863): Bitmap total bytes: 439318
D/LeakCanary(10863): Large bitmap count: 0
D/LeakCanary(10863): Large bitmap total bytes: 0
D/LeakCanary(10863): Db 1: open /data/user/0/com.example.dgr_app/no_backup/androidx.work.workdb
D/LeakCanary(10863): Stats: LruCache[maxSize=3000,hits=132021,misses=266189,hitRate=33%]
D/LeakCanary(10863): RandomAccess[bytes=13324152,reads=266189,travel=96267757709,range=39674726,size=48257770]
D/LeakCanary(10863): Heap dump reason: 5 retained objects, app is not visible
D/LeakCanary(10863): Analysis duration: 6934 ms
D/LeakCanary(10863): Heap dump file path: /storage/emulated/0/Download/leakcanary-com.example.dgr_app/2024-01-18_13-43-51_357.hprof
D/LeakCanary(10863): Heap dump timestamp: 1705545840873
D/LeakCanary(10863): Heap dump duration: 1391 ms

**Comment by tipsy-tips** [comment]
Please do try the built project, since the canary error does not show there and only shows on debugging build.

**Comment by samargy** [comment]
The crash only happens in debugging build?

**Comment by tipsy-tips** [comment]
Yes, it does on my end. So far no performance issues and errors

**Comment by samargy** [comment]
Seems to still crash when built on Android 14. What phone are you running it on? Also what are you using to get build logs?

**Comment by axelasa** [comment]
Hello everyone,
Having this issue whenever i cancelled a trip or navigation the app will freeze for a moment and will show that canary found a leak. The app continue to work after dumping the error however the app sometimes consistently show a prompt that it is not responding.
Below is a print analysis of the leaks that I am experiencing, and any help to solve this will be much appreciated.
 ​
D/LeakCanary(10405): ====================================
D/LeakCanary(10405): HEAP ANALYSIS RESULT
D/LeakCanary(10405): ====================================
D/LeakCanary(10405): 1 APPLICATION LEAKS
D/LeakCanary(10405): 
D/LeakCanary(10405): References underlined with "~~~" are likely causes.
D/LeakCanary(10405): Learn more at https://squ.re/leaks.
D/LeakCanary(10405): 
D/LeakCanary(10405): 896516 bytes retained by leaking objects
D/LeakCanary(10405): Signature: 37f15b5a051deab884265aa64df7c089bb978ef5
D/LeakCanary(10405): ┬───
D/LeakCanary(10405): │ GC Root: System class
D/LeakCanary(10405): │
D/LeakCanary(10405): ├─ android.provider.FontsContract class
D/LeakCanary(10405): │    Leaking: NO (Application↓ is not leaking and a class is never leaking)
D/LeakCanary(10405): │    ↓ static FontsContract.sContext
D/LeakCanary(10405): ├─ android.app.Application instance
D/LeakCanary(10405): │    Leaking: NO (Application is a singleton)
D/LeakCanary(10405): │    mBase instance of android.app.ContextImpl
D/LeakCanary(10405): │    ↓ Application.mLoadedApk
D/LeakCanary(10405): │                  ~~~~~~~~~~
D/LeakCanary(10405): ├─ android.app.LoadedApk instance
D/LeakCanary(10405): │    Leaking: UNKNOWN
D/LeakCanary(10405): │    Retaining 902.7 kB in 12309 objects
D/LeakCanary(10405): │    mApplication instance of android.app.Application
D/LeakCanary(10405): │    Receivers
D/LeakCanary(10405): │    ..Application@321199648
D/LeakCanary(10405): │    ....LocationServiceImpl$LocationModeChangedBroadcastReceiver@332607368
D/LeakCanary(10405): │    ....VisibilityTracker@332607432
D/LeakCanary(10405): │    ....AndroidBatteryMonitor$broadcastReceiver$1@332607504
D/LeakCanary(10405): │    ....ConnectionChangeReceiver@332607568
D/LeakCanary(10405): │    ..NavigationActivity@331552464
D/LeakCanary(10405): │    ....NavigationActivity$onCreate$3@331553008
D/LeakCanary(10405): │    ....NavigationActivity$onCreate$4@331553072
D/LeakCanary(10405): │    ↓ LoadedApk.mReceivers
D/LeakCanary(10405): │                ~~~~~~~~~~
D/LeakCanary(10405): ├─ android.util.ArrayMap instance
D/LeakCanary(10405): │    Leaking: UNKNOWN
D/LeakCanary(10405): │    Retaining 899.2 kB in 12246 objects
D/LeakCanary(10405): │    ↓ ArrayMap.mArray
D/LeakCanary(10405): │               ~~~~~~
D/LeakCanary(10405): ├─ java.lang.Object[] array
D/LeakCanary(10405): │    Leaking: UNKNOWN
D/LeakCanary(10405): │    Retaining 899.2 kB in 12244 objects
D/LeakCanary(10405): │    ↓ Object[2]
D/LeakCanary(10405): │            ~~~
D/LeakCanary(10405): ╰→ com.eopeter.fluttermapboxnavigation.activity.NavigationActivity instance
D/LeakCanary(10405): ​     Leaking: YES (ObjectWatcher was watching this because com.eopeter.fluttermapboxnavigation.activity.
D/LeakCanary(10405): ​     NavigationActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
D/LeakCanary(10405): ​     Retaining 896.5 kB in 12213 objects
D/LeakCanary(10405): ​     key = 025df42c-efe0-4d4f-8cfe-e3d338743b2b
D/LeakCanary(10405): ​     watchDurationMillis = 5643
D/LeakCanary(10405): ​     retainedDurationMillis = 639
D/LeakCanary(10405): ​     mApplication instance of android.app.Application
D/LeakCanary(10405): ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
D/LeakCanary(10405): ====================================
D/LeakCanary(10405): 0 LIBRARY LEAKS
D/LeakCanary(10405): 
D/LeakCanary(10405): A Library Leak is a leak caused by a known bug in 3rd party code that you do not have control over.
D/LeakCanary(10405): See https://square.github.io/leakcanary/fundamentals-how-leakcanary-works/#4-categorizing-leaks
D/LeakCanary(10405): ====================================
D/LeakCanary(10405): 0 UNREACHABLE OBJECTS
D/LeakCanary(10405): 
D/LeakCanary(10405): An unreachable object is still in memory but LeakCanary could not find a strong reference path
D/LeakCanary(10405): from GC roots.
D/LeakCanary(10405): ====================================
D/LeakCanary(10405): METADATA
D/LeakCanary(10405): 
D/LeakCanary(10405): Please include this in bug reports and Stack Overflow questions.
D/LeakCanary(10405): 
D/LeakCanary(10405): Build.VERSION.SDK_INT: 31
D/LeakCanary(10405): Build.MANUFACTURER: Google
D/LeakCanary(10405): LeakCanary version: 2.9.1
D/LeakCanary(10405): App process name: com.example.live_location_tracker_mapbox
D/LeakCanary(10405): Class count: 31781
D/LeakCanary(10405): Instance count: 309684
D/LeakCanary(10405): Primitive array count: 175117
D/LeakCanary(10405): Object array count: 44191
D/LeakCanary(10405): Thread count: 77
D/LeakCanary(10405): Heap total bytes: 34259963
D/LeakCanary(10405): Bitmap count: 10
D/LeakCanary(10405): Bitmap total bytes: 16019512
D/LeakCanary(10405): Large bitmap count: 0
D/LeakCanary(10405): Large bitmap total bytes: 0
D/LeakCanary(10405): Db 1: open /data/user/0/com.example.live_location_tracker_mapbox/databases/firestore.%5BDEFAULT%5D.live-tracker-mapbox.
D/LeakCanary(10405): %28default%29
D/LeakCanary(10405): Db 2: open /data/user/0/com.example.live_location_tracker_mapbox/no_backup/androidx.work.workdb
D/LeakCanary(10405): Count of retained yet cleared: 1 KeyedWeakReference instances
D/LeakCanary(10405): Stats: LruCache[maxSize=3000,hits=133099,misses=279638,hitRate=32%]
D/LeakCanary(10405): RandomAccess[bytes=14219423,reads=279638,travel=111318316505,range=42474599,size=50991548]
D/LeakCanary(10405): Analysis duration: 346047 ms
D/LeakCanary(10405): Heap dump file path: /storage/emulated/0/Download/leakcanary-com.example.
D/LeakCanary(10405): live_location_tracker_mapbox/2024-01-18_09-58-05_953.hprof
D/LeakCanary(10405): Heap dump timestamp: 1705561479760
D/LeakCanary(10405): Heap dump duration: Unknown
D/LeakCanary(10405): ====================================
I/Mapbox  (10405): [threading]: Worker 2 priority is now 4

**Comment by eopeter** [comment]
Stale issue message
